In [ ]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('user_behavior_dataset.csv')

In [7]:
# 方法
data.head()  # Display the first few rows of the dataset
# 属性
data.head

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,1,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,2,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,3,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,4,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,5,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3

In [22]:
data.tail()  # Display the last few rows of the dataset

,User ID,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
695,696,iPhone 12,iOS,92,3.9,1082,26,381,22,Male,2
696,697,Xiaomi Mi 11,Android,316,6.8,1965,68,1201,59,Male,4
697,698,Google Pixel 5,Android,99,3.1,942,22,457,50,Female,2
698,699,Samsung Galaxy S21,Android,62,1.7,431,13,224,44,Male,1
699,700,OnePlus 9,Android,212,5.4,1306,49,828,23,Female,3

In [19]:
# 方法
data.describe()  # Get a statistical summary of the dataset
# 属性
# data.describe

,User ID,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,User Behavior Class
count,700.00000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
mean,350.50000,271.128571,5.272714,1525.158571,50.681429,929.742857,38.482857,2.990000
std,202.21688,177.199484,3.068584,819.136414,26.943324,640.451729,12.012916,1.401476
min,1.00000,30.000000,1.000000,302.000000,10.000000,102.000000,18.000000,1.000000
25%,175.75000,113.250000,2.500000,722.250000,26.000000,373.000000,28.000000,2.000000
50%,350.50000,227.500000,4.900000,1502.500000,49.000000,823.500000,38.000000,3.000000
75%,525.25000,434.250000,7.400000,2229.500000,74.000000,1341.000000,49.000000,4.000000
max,700.00000,598.000000,12.000000,2993.000000,99.000000,2497.000000,59.000000,5.000000

In [ ]:
data.info()  # 获取colum 的数据类型

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 11 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   User ID                     700 non-null    int64
 1   Device Model                700 non-null    object
 2   Operating System            700 non-null    object
 3   App Usage Time (min/day)    700 non-null    int64
 4   Screen On Time (hours/day)  700 non-null    float64
 5   Battery Drain (mAh/day)     700 non-null    int64
 6   Number of Apps Installed    700 non-null    int64
 7   Data Usage (MB/day)         700 non-null    int64
 8   Age                         700 non-null    int64
 9   Gender                      700 non-null    object
 10  User Behavior Class         700 non-null    int64
dtypes: float64(1), int64(7), object(3)
memory usage: 60.3+ KB

In [ ]:
data.columns  # 获取所有的列名

Index(['User ID', 'Device Model', 'Operating System',
       'App Usage Time (min/day)', 'Screen On Time (hours/day)',
       'Battery Drain (mAh/day)', 'Number of Apps Installed',
       'Data Usage (MB/day)', 'Age', 'Gender', 'User Behavior Class'],
      dtype='object')

In [23]:
data.Age  # 获取Age列的数据
data['Age']  # 获取Age列的数据，另一种方式

0      40
1      47
2      42
3      20
4      31
       ..
695    22
696    59
697    50
698    44
699    23
Name: Age, Length: 700, dtype: int64

In [25]:
data['Device Model']  # 获取Device列的数据

0          Google Pixel 5
1               OnePlus 9
2            Xiaomi Mi 11
3          Google Pixel 5
4               iPhone 12
              ...
695             iPhone 12
696          Xiaomi Mi 11
697        Google Pixel 5
698    Samsung Galaxy S21
699             OnePlus 9
Name: Device Model, Length: 700, dtype: object

In [29]:
# data = data.drop("User ID", axis=1)  # 删除User ID列   0：行 1：列
# data = data.drop(columns=['User ID'])  # 删除User ID列的另一种方式

# 查看是否删除成功
data.head()

,Device Model,Operating System,App Usage Time (min/day),Screen On Time (hours/day),Battery Drain (mAh/day),Number of Apps Installed,Data Usage (MB/day),Age,Gender,User Behavior Class
0,Google Pixel 5,Android,393,6.4,1872,67,1122,40,Male,4
1,OnePlus 9,Android,268,4.7,1331,42,944,47,Female,3
2,Xiaomi Mi 11,Android,154,4.0,761,32,322,42,Male,2
3,Google Pixel 5,Android,239,4.8,1676,56,871,20,Male,3
4,iPhone 12,iOS,187,4.3,1367,58,988,31,Female,3

In [ ]:
# 基于索引
data.loc[1] # 查看索引为2的内容

Device Model                  OnePlus 9
Operating System                Android
App Usage Time (min/day)            268
Screen On Time (hours/day)          4.7
Battery Drain (mAh/day)            1331
Number of Apps Installed             42
Data Usage (MB/day)                 944
Age                                  47
Gender                           Female
User Behavior Class                   3
Name: 1, dtype: object

In [ ]:
# 基于位置
data.iloc[3]  # 获取第3行
# data.iloc[3:5]  # 获取3到4行
# data.iloc[3:5, 0:2]  # 获取3到4行和前两列
# data.iloc[3:5, [0, 2]]  # 获取3到4行和第0列和第2列
# data.iloc[3:5, [0, 2, 4]]  # 获取3到4行和第0列、第2列和第4列
# data.iloc[3:5, ['User ID', 'Age']]  # 获取3到4行和'User ID'列和'Age'列
# data.iloc[3:5, ['User ID', 'Age', 'Device Model']]  # 获取3到4行和'User ID'列、'Age'列和'Device Model'列

Device Model                  Google Pixel 5
Operating System                     Android
App Usage Time (min/day)                 239
Screen On Time (hours/day)               4.8
Battery Drain (mAh/day)                 1676
Number of Apps Installed                  56
Data Usage (MB/day)                      871
Age                                       20
Gender                                  Male
User Behavior Class                        3
Name: 3, dtype: object